name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 11 * * 1,3,5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms7-t0-7260-2
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_ABOOT_202012)
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_202012)
    displayName: "py_saithrift URL"

  # Test Control Parameters to skip or include directories
  - name: TEST_CONTROL_SKIP
    type: string
    default: 'platform_tests'
    displayName: "SKIP Directories List"
  - name: TEST_CONTROL_INCLUDE
    type: string
    default: ' '
    displayName: "INCLUDE Directories List"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      TEST_CONTROL_SKIP: ${{ parameters.TEST_CONTROL_SKIP }}
      TEST_CONTROL_INCLUDE: ${{ parameters.TEST_CONTROL_INCLUDE }}
