trigger: none
pr: none

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
  - repository: https://mssonic@dev.azure.com/mssonic/internal/_git/sonic-metadata
    type: git
    name: sonic-metadata
    ref: master

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
- name: TESTBED_NAME
  type: string
  default: vms7-t0-7260-1
  displayName: "Testbed Name"

- name: UPGRADE_TYPE
  type: string
  displayName: "Type of upgrade"
  default: warm,fast,cold
  values:
  - warm
  - fast
  - cold
  - warm,fast
  - warm,fast,cold

- name: FROM_IMAGE_LIST
  type: string
  default: latest
  displayName: "All base image numbers (space separated)"

- name: FROM_IMAGE_URL
  displayName: "Base image location"
  type: string
  default: $(IMAGE_BRCM_ABOOT_201811)
  values:
  - $(IMAGE_BRCM_ABOOT_201811)
  - $(IMAGE_BRCM_ABOOT_201911)
  - $(IMAGE_BRCM_ABOOT_202012)
  - $(IMAGE_BRCM_ABOOT_202106)
  - $(IMAGE_BRCM_ABOOT_PUBLIC)

- name: TO_IMAGE_LIST
  type: string
  default: latest
  displayName: "All target image numbers (space separated)"

- name: TO_IMAGE_URL
  displayName: "Target image location"
  type: string
  default: $(IMAGE_BRCM_ABOOT_202012)
  values:
  - $(IMAGE_BRCM_ABOOT_201811)
  - $(IMAGE_BRCM_ABOOT_201911)
  - $(IMAGE_BRCM_ABOOT_202012)
  - $(IMAGE_BRCM_ABOOT_202106)
  - $(IMAGE_BRCM_ABOOT_PUBLIC)

stages:
  - template: ../metadata_upgrade_template.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      UPGRADE_TYPE: ${{ parameters.UPGRADE_TYPE }}
      FROM_IMAGE_LIST: ${{ parameters.FROM_IMAGE_LIST }}
      FROM_IMAGE_URL: ${{ parameters.FROM_IMAGE_URL }}
      TO_IMAGE_LIST: ${{ parameters.TO_IMAGE_LIST }}
      TO_IMAGE_URL: ${{ parameters.TO_IMAGE_URL }}
