# Manually triggered pipeline used by Kavin Kamaraj
name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

# No scheduler configured. This pipeline can only be manually triggered.

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms17-t0-3800-azd
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: " "
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: " "
    displayName: "py_saithrift URL"

  - name: SKIP_SCRIPTS
    type: string
    default: "mvrf/test_mgmtvrf.py vrf/test_vrf.py vrf/test_vrf_attr.py system_health/test_system_health.py platform_tests/link_flap/test_cont_link_flap.py platform_tests/test_advanced_reboot.py"
    displayName: "Skip Scripts"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
