
name: RepoSync_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

variables:
  msazure_sonic_mgmt_branch: internal
  mssonic_sonic_mgmt_branch: internal

schedules:
  - cron: "45 3 * * *"
    displayName: Sync sonic-mgmt Repo
    branches:
      include:
        - internal
    always: true

stages:

  - stage: RepoSync
    jobs:

      - job: sonic_mgmt_sync
        pool: nightly
        timeoutInMinutes: 30
        variables:
          - group: GIT_SECRETS

        steps:

          - script: |
              set -xe

              MSAZURE_SONIC_MGMT_URL="https://${MSAZURE_USERNAME}:${MSAZURE_TOKEN}@msazure.visualstudio.com/DefaultCollection/One/_git/Networking-acs-sonic-mgmt"
              MSSONIC_SONIC_MGMT_URL="https://reposync:${MSSONIC_TOKEN}@dev.azure.com/mssonic/internal/_git/sonic-mgmt-int"

              msazure_branch=${{ variables.msazure_sonic_mgmt_branch }}
              mssonic_branch=${{ variables.mssonic_sonic_mgmt_branch }}

              src_branch=src_${msazure_branch}

              echo "=== Sync from msazure Networking-acs-sonic-mgmt:${msazure_branch} to mssonic sonic-mgmt-int:${mssonic_branch} ... ==="

              git config --global user.email "svc-acs@microsoft.com"
              git config --global user.name "SONiC Automation"

              git remote remove msazure || true
              git remote remove mssonic || true

              git remote add msazure ${MSAZURE_SONIC_MGMT_URL}
              git remote add mssonic ${MSSONIC_SONIC_MGMT_URL}

              git fetch msazure -t
              git fetch mssonic -t

              git branch -D ${src_branch} || true
              git checkout -b ${src_branch} msazure/${msazure_branch}
              git push --force mssonic HEAD:${mssonic_branch}
              git gc --auto || true
              echo "=== Sync sonic-mgmt succeeded ==="
            env:
              MSAZURE_USERNAME: $(MSAZURE_USERNAME)
              MSAZURE_TOKEN: $(MSAZURE_TOKEN)
              MSSONIC_TOKEN: $(MSSONIC_TOKEN)
            displayName: Sync sonic-mgmt
